repos:
  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
      - id: bandit
        args: ['--severity-level', 'medium', '--confidence-level', 'medium', '-q']
        exclude: ^(_deprecated_|tests/|backend/tests/|temporarily_|check_chirp|setup_tts|test_connector|test_password)
        types: [python]
